spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./data/h2db
    username: user
#    password: pw
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
#app:
#  ms:
#    monolith-api:
#      uuid: e00f35de-2bf9-4cb0-96a2-a43f16198c35